env:
  global:
    - GITHUB_TOKEN=8d707dde6a5dbc91f33ff31a1ea1cef6852be4a0
    - TIMEOUT=1000


sudo: false
dist: trusty
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run test --watchAll
after_success:
before_deploy:
- npm run build


# safelist
branches:
  only:
  - master
  - stable

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master